spring:
  jpa:
    show-sql: true
    hibernate:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: